In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
import time

In [2]:
# from PIL import ImageGrab
path = './Assets/images'
images = []
classNames = []
myList = os.listdir(path)
print(myList)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['jeeva.jpg', 'Manoj.jpg', 'Mugesh.jpg']
['jeeva', 'Manoj', 'Mugesh']


In [3]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList


In [4]:
encodeListKnown = findEncodings(images)
print('Encoding Complete')
timeout = time.time() + 10
cap = cv2.VideoCapture(0)
frames = 0

Encoding Complete


In [5]:
while time.time() < timeout:
    success, img = cap.read()
    #img = captureScreen()
    imgS = cv2.resize(img, (0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)
    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)



        if faceDis[matchIndex] < 0.50:
            name = classNames[matchIndex].upper()
            print(name)
                
        else:
            name = 'Unknown'
            print(name)
        frames += 1
        y1, x2, y2, x1 = faceLoc
        y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)
        cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)

    cv2.imshow('Webcam',img)
    cv2.waitKey(1)
cap.release()
cv2.destroyAllWindows()
    

[0.49030265 0.76637159 0.66943321]
JEEVA
[0.51198605 0.79158103 0.66059247]
Unknown
[0.40731017 0.79680114 0.73728691]
JEEVA
[0.40791018 0.79546726 0.71265517]
JEEVA


In [15]:
name

'JEEVANANTHAM'

In [19]:
name

'JEEVANANTHAM'